[app]
host = "0.0.0.0"
port = 8080
secret_key = "b1121d6c210689b31aba3b5c74f379e2f2c2ed4e7abbfe4deb9faaa125417d61"
debug = false
database_path = "dsfm.sqlite3"

[security]
session_cookie_secure = false
session_cookie_samesite = "Strict"

[telegram]
# Inserisci il token qui oppure usa DSFM_BOT_TOKEN da environment
bot_token = "8562855557:AAHjdKd7fPkx67yEibBfTvxfdBtoJJFXJsk"
polling_timeout = 20
